---
version: "3"

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ~/apps/mongo2:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=idp
      - MONGO_INITDB_ROOT_PASSWORD=idp
      - MONGO_INITDB_DATABASE=idp_db

  server:
    build:
      context: ./server
    image: server:1.0
    container_name: server
    ports:
      - "5000:5000"
      - "9350:9323"
    env_file: ./server/.env
    restart: on-failure
    depends_on:
      - mongo
      
  client:
    build:
      context: ./client
    image: client:1.0
    container_name: client
    ports:
      - "3000:3000"
      - "9351:9323"
    env_file: ./client/.env
    restart: on-failure
    depends_on:
      - mongo

